### ISSUE TITLE
Team: 2 students

### ISSUE THREAD

**Issue by alef-garrido** [alef-garrido/space-travellers-hub#21]
https://github.com/alef-garrido/space-travellers-hub

In this team there are only 2 people.

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] some of the cards are not yet implemented as mentioned in the requirements, please add the cards listed below:
 - the card "[1pt] Create basic structure for Rockets - Setup"
 - the card "[1pt] Create empty My profile - Setup (group task)"
 - the card "[1pt] Create website header with empty nav - Setup (group task)"
 - the card "[1pt] Create app and install basic dependencies - Setup (group task)"

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by VICTOR-CHUKWU** [comment]
Hi Team, 
# STATUS: APPROVED! 🥇 💯 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alef-garrido** [comment]
Thank you!
